### ISSUE TITLE
Method not found exception using Stashbox.Mocking.Moq with Stashbox 5.16.0

### ISSUE THREAD

**Issue by mtmelvin** [z4kn4fein/stashbox-mocking#3]
When using Stashbox.Mocking.Moq with Stashbox 5.16.0, `StashMoq.Create()` throws `System.MissingMethodException: 'Method not found: 'Void Stashbox.IStashboxContainer.RegisterResolver(Stashbox.Resolution.IResolver)'.'`

However, everything works fine after downgrading Stashbox to 5.15.0.

I have a simple reproduction project here: https://github.com/mtmelvin/stashmoq-missing-method-error-repro

If it makes any difference, I am using Visual Studio 17.11.2, .NET SDK 8.0.400, and have Resharper installed.

Please let me know if there's anything I can add that would be helpful.

**Comment by z4kn4fein** [comment]
Hey @mtmelvin, thank you for reporting this issue! I've released the fix in `v4.8.0`. Could you please check that it works at your end, too? Thanks!

**Comment by mtmelvin** [comment]
Looks great. Thank you so much!
